### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by qgmzmy** [badnng/Automatic_flashing_the_Magisk_Delta#1]

**Comment by badnng** [comment]
请打开命令提示符，然后使用命令提示符的窗口进行运行，然后将错误位置的截图给我即可
需要说明打开过程，Windows系统版本（需要包含多少位）和文件是否完全

**Comment by qgmzmy** [comment]
> 请打开命令提示符，然后使用命令提示符的窗口进行运行，然后将错误位置的截图给我即可 需要说明打开过程，Windows系统版本（需要包含多少位）和文件是否完全

直接运行的bat脚本，闪了一下就消失了，似乎有提示什么东西不是内部或外部命令，运行en的话还会打开Magisk.zip

**Comment by badnng** [comment]
您加我微信，咱微信详说：
mc_nng_block

**Comment by badnng** [comment]
抱歉，咱知道原因了

**Comment by badnng** [comment]
但还是加下微信好吧

**Comment by badnng** [comment]
抱歉，已经修复了，您重新下载新发布的zip文件重试~
