### ISSUE TITLE
关于adb刷入root权限的指令，尤其是天玑9200+平台的用户

### ISSUE THREAD

**Issue by sammary114** [badnng/Automatic_flashing_the_Magisk_Delta#5]
出厂安卓12及之前的骁龙芯片，`fastboot flash boot file.img`
出厂安卓13的骁龙芯片，`fastboot flash init_boot file.img`
出厂安卓13的天玑9200+，`fastboot flash init_boot_ab file.img`
or `fastboot flash init_boot_a file.img`
or `fastboot flash init_boot_b file.img`
尤其是K60至尊版的朋友们，一定要注意加上`_ab` (后者两条命令取决定于分区在哪个槽位选择)

**Comment by badnng** [comment]
那么，文件是一个init_boot吗，然后刷入到ab分区

**Comment by zlh953662526** [comment]
参考如图![ecf27102d4fc14b1b491e873d4e797d6.jpeg](https://github.com/badnng/Automatic_flashing_the_Magisk_Delta/assets/83531119/5fb2cd65-a49b-4664-a706-ee478d582ed5)

**Comment by sammary114** [comment]
> 那么，文件是一个init_boot吗，然后刷入到ab分区

是，联发科要`init_boot_a`或`init_boot_b`或`init_boot_ab`
![ecf27102d4fc14b1b491e873d4e797d6.jpeg](https://github.com/badnng/Automatic_flashing_the_Magisk_Delta/assets/83531119/e6564ead-4099-4e5c-97cf-164bced50476)

[具体文章在这](https://www.coolapk.com/feed/49907836?shareKey=M2QxOWU2ZjU0NjcwNjUyNzdkOGE~)

**Comment by badnng** [comment]
> > 那么，文件是一个init_boot吗，然后刷入到ab分区
> 
> 是，联发科要`init_boot_a`或`init_boot_b`或`init_boot_ab`
> ![ecf27102d4fc14b1b491e873d4e797d6.jpeg](https://github.com/badnng/Automatic_flashing_the_Magisk_Delta/assets/83531119/e6564ead-4099-4e5c-97cf-164bced50476)
> 
> [具体文章在这](https://www.coolapk.com/feed/49907836?shareKey=M2QxOWU2ZjU0NjcwNjUyNzdkOGE~)

好的，会在代码优化之后加入新功能

**Comment by badnng** [comment]
> > 那么，文件是一个init_boot吗，然后刷入到ab分区
> 
> 是，联发科要`init_boot_a`或`init_boot_b`或`init_boot_ab` ![ecf27102d4fc14b1b491e873d4e797d6.jpeg](https://private-user-images.githubusercontent.com/83531119/274487333-e6564ead-4099-4e5c-97cf-164bced50476.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Mjg3MzQsIm5iZiI6MTcwMDkyODQzNCwicGF0aCI6Ii84MzUzMTExOS8yNzQ0ODczMzMtZTY1NjRlYWQtNDA5OS00ZTVjLTk3Y2YtMTY0YmNlZDUwNDc2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNjA3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRhYmFlOTU5NDk5ODM0ZWY5ZTJhMTAzZTlmNjIwNDVkY2YyYzIzZDVjNTQxMTcxMWYxNjhhNTMwZTE5NmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K_IuzInCtuXfqZMoCXIVN5ZUQsXqyWkwb2rUgg7K5Yw)
> 
> [具体文章在这](https://www.coolapk.com/feed/49907836?shareKey=M2QxOWU2ZjU0NjcwNjUyNzdkOGE~)

![image](https://github.com/badnng/Automatic_flashing_the_Magisk_Delta/assets/115983722/0be4ee8a-8472-4e35-bae1-eca299e86eac)
已融合，将会在V2.0版本中实装

**Comment by badnng** [comment]
> > 那么，文件是一个init_boot吗，然后刷入到ab分区
> 
> 是，联发科要`init_boot_a`或`init_boot_b`或`init_boot_ab` ![ecf27102d4fc14b1b491e873d4e797d6.jpeg](https://private-user-images.githubusercontent.com/83531119/274487333-e6564ead-4099-4e5c-97cf-164bced50476.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzM4MjIsIm5iZiI6MTcwMDkzMzUyMiwicGF0aCI6Ii84MzUzMTExOS8yNzQ0ODczMzMtZTY1NjRlYWQtNDA5OS00ZTVjLTk3Y2YtMTY0YmNlZDUwNDc2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNzMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmU1YjAxMzQ3ODJhZmFiOGI5NWU3N2Q3YTIzZjU0NTc0MGFlNzYyZjA1MWNhMDE3NTc4MDI1ZjY1NmMzY2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WRQnuZPOJbIKbLtL3SJbOEWV7Q7Wde2dT0xE4d1CWns)
> 
> [具体文章在这](https://www.coolapk.com/feed/49907836?shareKey=M2QxOWU2ZjU0NjcwNjUyNzdkOGE~)

已Pull Origin
