### ISSUE TITLE
刷入无效

### ISSUE THREAD

**Issue by qgmzmy** [badnng/Automatic_flashing_the_Magisk_Delta#6]
机型 Pixel 5，选项选择的a，运行后任未获取Root。可以确定是61行的boot_ab造成的，删除_ab后运行一切正常
![image](https://github.com/badnng/Automatic_flashing_the_Magisk/assets/114319143/fd8b7ed7-f358-43ab-98af-6991df153844)

**Comment by badnng** [comment]
_~~好久没看github了~~_
这应该是执行顺序的问题
init_boot应该不受影响
boot_ab和boot调换位置即可
_（虽然会执行两次罢了）_
下个版本修复
~~争取春节前~~

**Comment by badnng** [comment]
> 机型 Pixel 5，选项选择的a，运行后任未获取Root。可以确定是61行的boot_ab造成的，删除_ab后运行一切正常 ![image](https://private-user-images.githubusercontent.com/114319143/294322172-fd8b7ed7-f358-43ab-98af-6991df153844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODE0NTYsIm5iZiI6MTcwNjg4MTE1NiwicGF0aCI6Ii8xMTQzMTkxNDMvMjk0MzIyMTcyLWZkOGI3ZWQ3LWYzNTgtNDNhYi05OGFmLTY5OTFkZjE1Mzg0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxMzM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjUwYTljZjUxMGRlOWY4N2I1M2JkYTlhYmJkYmMwMTM0NmFjOTMxMmEwMDQzYWFlNGJlY2Y1NjJlZjAzZjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jm86JiCf10umBHNnS8h0c4S6w3TKEm3bRx3MabDiWSo)

已修复#6
https://github.com/badnng/Automatic_flashing_the_Magisk/releases/tag/Release_2.0
